# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://docs.travis-ci.com/user/languages/r/

language: r
cache: packages

r:
  - release 

r_packages:
  - tikzDevice
  - minpack.lm
  - boot
  - Rcpp

apt_packages:
  - libgsl-dev  

sudo: required
dist: trusty

warnings_are_errors: false
use_bioc: true

notifications:
  email:
    on_success: change
    on_failure: change
          
env:
  global:
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --timings"
    - R_CHECK_TIME="TRUE"
    - R_CHECK_TESTS="TRUE"
    - _R_CHECK_TIMINGS_="0"

r_binary_packages:
  - devtools
  - roxygen2

after_success:
  - Rscript -e 'devtools::install(); devtools::test()'
