#!/bin/bash

set -e
set -u

while getopts "qch" opt; do
	case $opt in
		q)
			Rscript --vanilla -e "devtools::install(quick=TRUE)"
			exit
			;;
		c)
			Rscript --vanilla -e "devtools::check(cran=TRUE)"
			exit
			;;
		h)
			echo -e "
			Install hadron package\n
			Usage: $0 [-q] [-h]\n
			-q: quick install
			-c: check CRAN
			-h: help\n"
			exit
			;;
	esac
done

./document
Rscript --vanilla -e "devtools::install()"
