#!/bin/bash
# Copyright © 2019 Martin Ueding <dev@martin-ueding.de>

set -e
set -u

cd .git

if ! [[ -d hooks ]]; then
  mkdir hooks
fi

cd hooks

for hook in ../../hooks/*; do
  basename="${hook##*/}"
  if ! [[ -f "$basename" ]]; then
    ln -vs "$hook" ./
  fi
done
