#! /bin/sh
if [ "$1" = "" ] || [ "$2" = "" ]; then
  echo "ERROR: pdfcat requires at least two arguments!"
  echo
  echo "USAGE: pdfcat outfile infile1 infile2 ... infileN"
  echo "       where 'outfile' and 'infileX' are the filenames of"
  echo "       the output file and input file(s) respectively"
  exit 1
fi

echo "pdfcat: output file: $1, input: $2 [...]"
gs -q -dAutoRotatePages=false -dNOPAUSE -dBATCH -sDEVICE=pdfwrite -sOutputFile=${@}
