#!/bin/bash
# Copyright © 2019 Martin Ueding <dev@martin-ueding.de>

# Builds the documentation with Roxygen and aborts the commit if the output of
# `git diff` changes. This gives the user the opportunity to add the generated
# changes and try to commit again.

set -e
set -u

red="$(tput setaf 1)"
reset="$(tput sgr0)"

diff_old=$(mktemp)
diff_new=$(mktemp)
status_old=$(mktemp)
status_new=$(mktemp)

cleanup() {
  rm -f "$diff_old"
  rm -f "$diff_new"
  rm -f "$status_old"
  rm -f "$status_new"
}

trap cleanup EXIT

git diff > "$diff_old"
git status --porcelain -u > "$status_old"
Rscript -e 'devtools::document();'
Rscript -e 'Rcpp::compileAttributes();'
git diff > "$diff_new"
git status --porcelain  -u> "$status_new"

if ! diff -q "$diff_old" "$diff_new" &> /dev/null; then
  echo "${red}Generating the documentation or Rcpp exports has changed the tree, add them to the index and try to commit again.${reset}" >&2
  git status
  exit 2
fi

if ! diff -q "$status_old" "$status_new" &> /dev/null; then
  echo "${red}Generating the documentation or Rcpp exports has added new files, add them to the index and try to commit again.${reset}" >&2
  git status -u
  exit 2
fi
