# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

read_nissa_textcf_kernel <- function(file_basenames_to_read, smear_combs_to_read, nts, combs_to_read) {
    .Call('_hadron_read_nissa_textcf_kernel', PACKAGE = 'hadron', file_basenames_to_read, smear_combs_to_read, nts, combs_to_read)
}

